apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-user-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-user
  template:
    metadata:
      labels:
        app: api-user
    spec:
      containers:
        - name: api-user
          image: jordanbmowry/udagram-api-user:latest
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: POSTGRES_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: POSTGRES_HOST
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: AWS_REGION
            - name: AWS_PROFILE
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: AWS_PROFILE
            - name: AWS_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: AWS_BUCKET
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: JWT_SECRET
            - name: URL
              value: 'http://localhost:8100'
